// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PicPay.Infrastructure.Persistence;

#nullable disable

namespace PicPay.Migrations
{
    [DbContext(typeof(DbConnection))]
    [Migration("20260214191455_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PicPay.Outer.Persistence.Schemas.TransactionSchema", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FkPayee")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FkPayer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("Type")
                        .HasColumnType("integer");

                    b.Property<string>("UserSchemaId")
                        .HasColumnType("text");

                    b.Property<string>("UserSchemaId1")
                        .HasColumnType("text");

                    b.Property<decimal>("Value")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("UserSchemaId");

                    b.HasIndex("UserSchemaId1");

                    b.ToTable("transactionSchema");
                });

            modelBuilder.Entity("PicPay.Outer.Persistence.Schemas.UserSchema", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<decimal>("Balance")
                        .HasColumnType("numeric");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("userSchema");
                });

            modelBuilder.Entity("PicPay.Outer.Persistence.Schemas.TransactionSchema", b =>
                {
                    b.HasOne("PicPay.Outer.Persistence.Schemas.UserSchema", null)
                        .WithMany("TransactionReceived")
                        .HasForeignKey("UserSchemaId");

                    b.HasOne("PicPay.Outer.Persistence.Schemas.UserSchema", null)
                        .WithMany("TransactionSent")
                        .HasForeignKey("UserSchemaId1");
                });

            modelBuilder.Entity("PicPay.Outer.Persistence.Schemas.UserSchema", b =>
                {
                    b.Navigation("TransactionReceived");

                    b.Navigation("TransactionSent");
                });
#pragma warning restore 612, 618
        }
    }
}
